Cleaning tools and "setup and run"
ur-whitelab/md-agent pull request #12
Opened 2023-06-19 20:30 UTC by Jgmedina95

2023-06-22 22:07 UTC, SamCox822 reviewed
In mdagent/tools/search_tools.py
can you change the prompt summary to use the BaseLanguageModel from langchain (it's also used in tools.py). We need to keep llm model types the same throughout

2023-06-22 22:16 UTC, SamCox822 requested changes

2023-06-22 22:16 UTC, SamCox822 commented on mdagent/tools/search_tools.py
Can you change the prompt summary to use the BaseLanguageModel from langchain (it's also used in tools.py). We need to keep llm model types the same throughout

2023-06-22 22:16 UTC, SamCox822 commented on notebooks/set_and_run_example.ipynb
Can you make this a full example that makes the params file and then runs?

2023-06-22 22:16 UTC, SamCox822 commented on environment.yaml
Since you have to add openmm and pdbfixer via conda, can you add those instructions on the readme under Installation?

2023-06-23 12:10 UTC, Jgmedina95 commented on mdagent/tools/search_tools.py
done

2023-06-23 13:12 UTC, Jgmedina95 commented on notebooks/set_and_run_example.ipynb
done

2023-06-23 13:15 UTC, Jgmedina95 commented on environment.yaml
done

2023-06-23 19:07 UTC, SamCox822 reviewed
I did a little rearranging and added a notebook that reflects a full user story.

2023-06-23 19:07 UTC, SamCox822 approved these changes

2023-06-23 19:22 UTC, merged